GET http://localhost:4000/articles/

###------     GET ALL Articles ---------------
GET http://localhost:4000/articles/article/allarticles

###------     CREATE USERS  -------------
POST http://localhost:4000/articles
Content-Type: application/json

{
    "title" : "shortage",
    "description" : "silicon shortage",
    "markdown" : "lol"
}



###-------  GET user by ID -----------
GET http://localhost:4000/articles/6148a243c2d08b2d50bb2ced